import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PollingService {

  getSomeData(n: number) {
    return n > 99 ? this.people : this.people.slice(0, n);
  }
//#region people MOCK DATA
  people = [{'id':1,'firstName':'Nikolaus','lastName':'Iannetti','email':'niannetti0@irs.gov'},
  {'id':2,'firstName':'Jelene','lastName':'Sackey','email':'jsackey1@google.com.au'},
  {'id':3,'firstName':'Filbert','lastName':'Bowering','email':'fbowering2@comcast.net'},
  {'id':4,'firstName':'Coreen','lastName':'Harriot','email':'charriot3@omniture.com'},
  {'id':5,'firstName':'Norina','lastName':'Roels','email':'nroels4@google.com.br'},
  {'id':6,'firstName':'Nannette','lastName':'Chinge de Hals','email':'nchingedehals5@live.com'},
  {'id':7,'firstName':'Shalna','lastName':'Beaze','email':'sbeaze6@un.org'},
  {'id':8,'firstName':'Cam','lastName':'Maudlen','email':'cmaudlen7@cbc.ca'},
  {'id':9,'firstName':'Enrica','lastName':'Knobell','email':'eknobell8@go.com'},
  {'id':10,'firstName':'Bobine','lastName':'Tuffrey','email':'btuffrey9@ed.gov'},
  {'id':11,'firstName':'Emelen','lastName':'Dixey','email':'edixeya@huffingtonpost.com'},
  {'id':12,'firstName':'Georgie','lastName':'Rix','email':'grixb@nymag.com'},
  {'id':13,'firstName':'Amalea','lastName':'Melliard','email':'amelliardc@rakuten.co.jp'},
  {'id':14,'firstName':'Delbert','lastName':'Girt','email':'dgirtd@g.co'},
  {'id':15,'firstName':'Panchito','lastName':'Keenan','email':'pkeenane@angelfire.com'},
  {'id':16,'firstName':'Sallee','lastName':'Patchett','email':'spatchettf@jalbum.net'},
  {'id':17,'firstName':'Reeba','lastName':'Rein','email':'rreing@tripadvisor.com'},
  {'id':18,'firstName':'Jenni','lastName':'Rewan','email':'jrewanh@go.com'},
  {'id':19,'firstName':'Loree','lastName':'Aylin','email':'laylini@webnode.com'},
  {'id':20,'firstName':'Dall','lastName':'Grummitt','email':'dgrummittj@weather.com'},
  {'id':21,'firstName':'Bee','lastName':'Stowe','email':'bstowek@list-manage.com'},
  {'id':22,'firstName':'Martainn','lastName':'Ballam','email':'mballaml@about.com'},
  {'id':23,'firstName':'Stearn','lastName':'Sheraton','email':'ssheratonm@spotify.com'},
  {'id':24,'firstName':'Noni','lastName':'Bartholomew','email':'nbartholomewn@yellowpages.com'},
  {'id':25,'firstName':'Lorene','lastName':'Sanders','email':'lsanderso@weather.com'},
  {'id':26,'firstName':'Dexter','lastName':'Barttrum','email':'dbarttrump@amazon.co.uk'},
  {'id':27,'firstName':'Saw','lastName':'Safell','email':'ssafellq@nps.gov'},
  {'id':28,'firstName':'Arabela','lastName':'Mea','email':'amear@biblegateway.com'},
  {'id':29,'firstName':'Lynda','lastName':'Olyfant','email':'lolyfants@symantec.com'},
  {'id':30,'firstName':'Jehu','lastName':'Fleet','email':'jfleett@amazon.co.jp'},
  {'id':31,'firstName':'Nicholle','lastName':'Parfrey','email':'nparfreyu@technorati.com'},
  {'id':32,'firstName':'Temple','lastName':'McNeil','email':'tmcneilv@eventbrite.com'},
  {'id':33,'firstName':'Trumaine','lastName':'Akitt','email':'takittw@weebly.com'},
  {'id':34,'firstName':'Kenny','lastName':'Brockington','email':'kbrockingtonx@trellian.com'},
  {'id':35,'firstName':'Mala','lastName':'Conachy','email':'mconachyy@xing.com'},
  {'id':36,'firstName':'Redford','lastName':'Tabram','email':'rtabramz@hud.gov'},
  {'id':37,'firstName':'Gayleen','lastName':'Bodycote','email':'gbodycote10@tumblr.com'},
  {'id':38,'firstName':'Son','lastName':'Hackin','email':'shackin11@cbsnews.com'},
  {'id':39,'firstName':'Auberon','lastName':'Bickerton','email':'abickerton12@sbwire.com'},
  {'id':40,'firstName':'Garrek','lastName':'Flecknoe','email':'gflecknoe13@eventbrite.com'},
  {'id':41,'firstName':'Denna','lastName':'Forgan','email':'dforgan14@narod.ru'},
  {'id':42,'firstName':'Arlena','lastName':'Ungaretti','email':'aungaretti15@ezinearticles.com'},
  {'id':43,'firstName':'Jermayne','lastName':'Averill','email':'javerill16@usatoday.com'},
  {'id':44,'firstName':'Amos','lastName':'Dunrige','email':'adunrige17@cnet.com'},
  {'id':45,'firstName':'Loren','lastName':'Parkes','email':'lparkes18@kickstarter.com'},
  {'id':46,'firstName':'Tabor','lastName':'Lamberton','email':'tlamberton19@timesonline.co.uk'},
  {'id':47,'firstName':'Sascha','lastName':'Levinge','email':'slevinge1a@tripadvisor.com'},
  {'id':48,'firstName':'Matthias','lastName':'Kinchin','email':'mkinchin1b@imgur.com'},
  {'id':49,'firstName':'Kerrill','lastName':'Pashenkov','email':'kpashenkov1c@vistaprint.com'},
  {'id':50,'firstName':'Elnora','lastName':'Narracott','email':'enarracott1d@examiner.com'},
  {'id':51,'firstName':'Caryn','lastName':'Garron','email':'cgarron1e@msu.edu'},
  {'id':52,'firstName':'Marsiella','lastName':'Courcey','email':'mcourcey1f@jiathis.com'},
  {'id':53,'firstName':'Farris','lastName':'Mushett','email':'fmushett1g@ehow.com'},
  {'id':54,'firstName':'Ring','lastName':'Fibben','email':'rfibben1h@freewebs.com'},
  {'id':55,'firstName':'Katlin','lastName':'Bromont','email':'kbromont1i@answers.com'},
  {'id':56,'firstName':'Zonda','lastName':'Badsey','email':'zbadsey1j@goo.ne.jp'},
  {'id':57,'firstName':'Edita','lastName':'Rubie','email':'erubie1k@slashdot.org'},
  {'id':58,'firstName':'Marie-ann','lastName':'Burt','email':'mburt1l@google.nl'},
  {'id':59,'firstName':'Kellia','lastName':'Trillo','email':'ktrillo1m@oracle.com'},
  {'id':60,'firstName':'Silvia','lastName':'Blumson','email':'sblumson1n@opera.com'},
  {'id':61,'firstName':'Gwenni','lastName':'Wilkerson','email':'gwilkerson1o@sourceforge.net'},
  {'id':62,'firstName':'Muriel','lastName':'Purple','email':'mpurple1p@digg.com'},
  {'id':63,'firstName':'Jessie','lastName':'Molyneux','email':'jmolyneux1q@intel.com'},
  {'id':64,'firstName':'Vinson','lastName':'McWhirter','email':'vmcwhirter1r@springer.com'},
  {'id':65,'firstName':'Barty','lastName':'Fossett','email':'bfossett1s@google.co.jp'},
  {'id':66,'firstName':'Basile','lastName':'Flowerden','email':'bflowerden1t@nytimes.com'},
  {'id':67,'firstName':'Jackelyn','lastName':'Jaine','email':'jjaine1u@example.com'},
  {'id':68,'firstName':'Curt','lastName':'Traves','email':'ctraves1v@ning.com'},
  {'id':69,'firstName':'Erny','lastName':'Glison','email':'eglison1w@google.ru'},
  {'id':70,'firstName':'Yurik','lastName':'Brimblecomb','email':'ybrimblecomb1x@theguardian.com'},
  {'id':71,'firstName':'Eleanora','lastName':'Bramstom','email':'ebramstom1y@theguardian.com'},
  {'id':72,'firstName':'Samson','lastName':'Sallis','email':'ssallis1z@purevolume.com'},
  {'id':73,'firstName':'Ainslee','lastName':'Armin','email':'aarmin20@mail.ru'},
  {'id':74,'firstName':'Dana','lastName':'Dartan','email':'ddartan21@unesco.org'},
  {'id':75,'firstName':'Ellie','lastName':'Hould','email':'ehould22@naver.com'},
  {'id':76,'firstName':'Joly','lastName':'Labbe','email':'jlabbe23@liveinternet.ru'},
  {'id':77,'firstName':'Alexina','lastName':'Grady','email':'agrady24@cyberchimps.com'},
  {'id':78,'firstName':'Jordon','lastName':'Youens','email':'jyouens25@stanford.edu'},
  {'id':79,'firstName':'Laurent','lastName':'Duckfield','email':'lduckfield26@xinhuanet.com'},
  {'id':80,'firstName':'Glynn','lastName':'Chate','email':'gchate27@icio.us'},
  {'id':81,'firstName':'Ruthi','lastName':'Morling','email':'rmorling28@gnu.org'},
  {'id':82,'firstName':'Thacher','lastName':'Dronsfield','email':'tdronsfield29@angelfire.com'},
  {'id':83,'firstName':'Lusa','lastName':'MacAlroy','email':'lmacalroy2a@indiatimes.com'},
  {'id':84,'firstName':'Taryn','lastName':'Emsley','email':'temsley2b@twitpic.com'},
  {'id':85,'firstName':'Tristam','lastName':'Blaine','email':'tblaine2c@senate.gov'},
  {'id':86,'firstName':'Levin','lastName':'Read','email':'lread2d@who.int'},
  {'id':87,'firstName':'Sutherlan','lastName':'Ladloe','email':'sladloe2e@paginegialle.it'},
  {'id':88,'firstName':'Estrellita','lastName':'Gulliver','email':'egulliver2f@forbes.com'},
  {'id':89,'firstName':'Sheilah','lastName':'Keightley','email':'skeightley2g@whitehouse.gov'},
  {'id':90,'firstName':'Garv','lastName':'Hatt','email':'ghatt2h@spotify.com'},
  {'id':91,'firstName':'Cassey','lastName':'Grattage','email':'cgrattage2i@unc.edu'},
  {'id':92,'firstName':'Seamus','lastName':'Esparza','email':'sesparza2j@gmpg.org'},
  {'id':93,'firstName':'Jeniece','lastName':'Wilber','email':'jwilber2k@webs.com'},
  {'id':94,'firstName':'Franciskus','lastName':'Badsworth','email':'fbadsworth2l@joomla.org'},
  {'id':95,'firstName':'Kellie','lastName':'Klaffs','email':'kklaffs2m@paypal.com'},
  {'id':96,'firstName':'Catriona','lastName':'Ripping','email':'cripping2n@vimeo.com'},
  {'id':97,'firstName':'Chaunce','lastName':'Turneaux','email':'cturneaux2o@phoca.cz'},
  {'id':98,'firstName':'Marylin','lastName':'Kaasman','email':'mkaasman2p@vimeo.com'},
  {'id':99,'firstName':'Nichole','lastName':'Easson','email':'neasson2q@google.pl'},
  {'id':100,'firstName':'Shaun','lastName':'Kobpa','email':'skobpa2r@newyorker.com'}];
  //#endregion MOCK DATA
}
